### ISSUE TITLE
Support for --net switch

### ISSUE THREAD

**Issue by csghuser** [test-kitchen/kitchen-docker#108]
Hi there, 

Many thanks for creating this excellent driver! Would it be possible to add an option to start containers with the --net switch, "--net host" for example? 

Without this, statements such as:
/sbin/sysctl -w net.ipv4.tcp_syncookies=1

Fail at the moment, as this does not appear to be exposed without setting the --net host switch. 

Not sure if this will break anything else however. 

Thanks!

**Comment by mwain** [comment]
See #213

**Comment by coderanger** [comment]
This is now supported via `run_options`.
