### ISSUE TITLE
Support SUSE platform

### ISSUE THREAD

**Issue by djdefi** [test-kitchen/kitchen-docker#120]
Wondering what it would take to support SUSE as a platform.

**Comment by alinadima** [comment]
Any news on that?

**Comment by CarpathianUA** [comment]
Any news on that?

**Comment by zuazo** [comment]
There is an open PR about it here: https://github.com/portertech/kitchen-docker/pull/156

But it has some conflicts and should be updated.

**Comment by CarpathianUA** [comment]
@zuazo, thanks for update
