### ISSUE TITLE
Consider changing order of Dockerfile commands

### ISSUE THREAD

**Issue by joerg** [test-kitchen/kitchen-docker#128]
We are testing our Environment with Docker on RedHat Linux which offers official Docker images. However, these images do not have a valid repository set.
Now if the provision commands would come before the base in the created Dockerfile it would be easy for us and we could simple add some commands to the .kitchen.yml. Currently we have to create a custom Dockerfile.erb which basically copies all you do and has three simple commands first to add our repo.
Maybe you could also add a pre_provision command set? If you like any of the ideas/wishes I could easily send you a pull request.

**Comment by jeffreycoe** [comment]
There is a `provision_command` config option which should provide the functionality you need. See more info here: https://github.com/test-kitchen/kitchen-docker#provision_command
