### ISSUE TITLE
Configure NO_PROXY parameter when starting kitchen docker test

### ISSUE THREAD

**Issue by dennyzhang** [test-kitchen/kitchen-docker#132]
Hi there

I'm using http proxy to fasten the docker test. For http request to localhost port, I want to avoid http proxy.

Checking related code, I doesn't seem to be able to configure NO_PROXY environment parameter. Any suggestions? Thanks!

https://github.com/portertech/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L241-L242
     cmd << " -e http_proxy=#{config[:http_proxy]}" if config[:http_proxy]
     cmd << " -e https_proxy=#{config[:https_proxy]}" if config[:https_proxy]

**Comment by pdaugavietis** [comment]
I think you mean this: https://github.com/test-kitchen/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L197

so you'll need to put this in the .kitchen.yml:
`
driver_config:
  http_proxy: http://x.x.x.x:8080
  https_proxy: http://x.x.x.x:8080
  no_proxy: localhost, another-host
`

**Comment by pdaugavietis** [comment]
@tnguyen14 sorry not sure - i'm not running chef-client (that I know of - don't know much about the internals :( ) but you should be able to set those to environment variables maybe, and then just set those env vars before a run on command line?

**Comment by jeffreycoe** [comment]
These settings should be able to be set through the Chef client_rb provisioner configuration (See the client_rb configuration in the docs here: https://docs.chef.io/workstation/config_yml_kitchen/), or there is support for environment variables with the 2.10 release of this gem.

Please open a new issue if there are any problems testing this functionality with the latest release. Thanks.
