### ISSUE TITLE
How to set default hostname with driver.instance.name 

### ISSUE THREAD

**Issue by snahelou** [test-kitchen/kitchen-docker#152]
Hi

Do you know if it's possible to set default hostname with the kitchen instance name by using kitchen configuration file ? 
I read that we can use a static name ( using "driver_config:hostname" key) but it seem it's not possible to use a variable name.

My need is to use the fact %hostname with puppet to choose the right hiera file, but it's not possible with the default docker name. So it will be usefull to set hostname like kitchen instance name. 

If it's not possible by using kitchen configuration file, this issue has already implemented for vagrant (https://github.com/test-kitchen/kitchen-vagrant/commit/e50d1460bbb3c7c43a6644e18a6223209ce86194 ) 

It's seems that we just need to add the following code in driver.rb  : 
      default_config :hostname do |driver|
        driver.instance.name
      end

Example: 
$ kitchen list
Instance                     Driver  Provisioner  Last Action
default-centos-66            Docker  PuppetApply  Converged
test-A-centos-66             Docker  PuppetApply  Created
$ kitchen login test-A-centos-66
kitchen@localhost's password: 
[kitchen@test-A-centos-66 ~]$ 

Thank you in advance !

**Comment by cdelgehier** [comment]
Yes, this option would be really very useful

Thank

**Comment by evanwieren** [comment]
This would be beneficial for me as well. Attempting to test a cookbook that uses the node.name attribute, and am unable to validate using kitchen.yml with Docker.
