### ISSUE TITLE
Run builds in Travis CI

### ISSUE THREAD

**Issue by sgerrand** [test-kitchen/kitchen-docker#161]
This project has a [configuration file for Travis CI](https://github.com/portertech/kitchen-docker/blob/f4c03cd57e63de33c5d6b4de874b329e6a462891/.travis.yml), but the project hasn't been activated there. :crying_cat_face:

**Comment by obazoud** [comment]
@sgerrand see https://github.com/zuazo/kitchen-in-travis

**Comment by peterabbott** [comment]
I've found it easier running CI builds in CircleCI, they have far better support for running Docker containers.

**Comment by peterabbott** [comment]
Here is an example of using CircleCI to push a new version to rubygems repo when all tests pass after a successful PR merge to master.

https://github.com/peterabbott/kitchen-docker_ssh/blob/master/circle.yml

**Comment by sgerrand** [comment]
@obazoud @petecheslock: I was really just referring to automatically running the unit tests, which [are mostly passing](https://travis-ci.org/sgerrand/kitchen-docker/builds/76789655). I'll leave the integration tests for someone else to pick up.

**Comment by jjasghar** [comment]
Closed via: b408e94

**Comment by sgerrand** [comment]
@jjasghar: Thank you! 💝
