### ISSUE TITLE
Unable test kitchen-docker on windows

### ISSUE THREAD

**Issue by phanikumar1210** [test-kitchen/kitchen-docker#188]
I was unable to test a cookbook on windows 8 Professional with docker I have installed test-kitchen, kitchen-docker gems but I am getting the following error.

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: You must first install the Docker CLI tool http://www.docker.io/gettingstarted/
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

I was wondering if anyone could help in sorting out this issue.

**Comment by gliptak** [comment]
see https://github.com/portertech/kitchen-docker/pull/182

after patching ```kitchen-docker```, you will still have ```sudo``` related issues with ```kitchen``` itself ...

**Comment by friism** [comment]
It looks like there's a bad default for Docker on Windows: https://github.com/test-kitchen/kitchen-docker/blob/988fb087d725c56e694b894b7db5cd3741042890/lib/kitchen/driver/docker.rb#L35

I posted on the Docker forums too: https://forums.docker.com/t/chef-test-kitchen-fails-to-find-docker-daemon/14501/4?u=friism

**Comment by billiechar** [comment]
Hi fiism, Thanks for replying on the Docker forums too. Is that file something we can edit locally? I can't find that file locally to make the changes. The only place that looked similar is docker-api-1.26.2, but changing that seemed to have little effect.

Cheers
Billie

**Comment by coderanger** [comment]
I'm going to close this out pending a more complete error report.
