### ISSUE TITLE
kitchen-docker does not set KITCHEN_* environment variables

### ISSUE THREAD

**Issue by thedrow** [test-kitchen/kitchen-docker#194]
Because omnibus is not supported with Linux Alpine I tried using Test-Kitchen 1.5's shell verifier.

As you can see at https://github.com/cl-lab-k/apache2-take/blob/shell_verifier/serverspec/spec_helper.rb serverspec needs those environment variables in order to connect with SSH to the machine.

**Comment by coderanger** [comment]
Setting those variables happens in the verifier itself (https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/verifier/shell.rb#L89-L98), not the driver. The issue might be that the docker driver sets different state keys than whichever other one you are looking at.

**Comment by thedrow** [comment]
How can we make it work then?

**Comment by coderanger** [comment]
Closing this out as I don't think there is any bug here.
