### ISSUE TITLE
Support for docker network

### ISSUE THREAD

**Issue by billietl** [test-kitchen/kitchen-docker#211]
In order to test clustering with kitchen and docker (like described in this article : https://matt-wrock.squarespace.com/blog/multi-node-testing-with-test-kitchen-and-docker) it would be neat to define a network for containers to connect to (like the networks key in docker-compose config files https://docs.docker.com/compose/networking/#specifying-custom-networks).

**Comment by coderanger** [comment]
This is now supported via `run_options`.

**Comment by waghanza** [comment]
@coderanger How can I enable network discovery ?
