### ISSUE TITLE
Kitchen cannot log into container if user has many keys in their ssh agent

### ISSUE THREAD

**Issue by Fitzsimmons** [test-kitchen/kitchen-docker#217]
I have a lot of ssh keys in my ssh agent, which means kitchen cannot log into my container. It tries all of the keys in my agent, eventually reaching the maximum number of authentications:

```
[SSH] opening connection to kitchen@localhost<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>32772, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"kitchen", :user=>"kitchen"}>
[SSH] connection failed (#<Net::SSH::Disconnect: disconnected: Too many authentication failures for kitchen (2)>)
```

It's trying to use password authentication, but ssh uses up all of my authentication attempts going through my agent's keys before it has a chance to get to password auth.

Why is password login used? The vagrant driver (for example) works fine because it uses keys only and effectively sets `IdentitiesOnly=yes`, preventing the ssh agent from being used. I also see that you go to the trouble of creating and seeding an ssh key into the container, but it doesn't seem to be used.

**Comment by coderanger** [comment]
If you set the SSH key to be used in your transport config it should work. This is a problem with OpenSSH too, I don't think there is a way to work around it on the client side other than for the driver to insert its key into the transport config directly.

**Comment by Fitzsimmons** [comment]
Confirmed that
```
transport:
  ssh_key: .kitchen/docker_id_rsa
```

In .kitchen.yml effectively works around this problem. Thanks.

**Comment by coderanger** [comment]
We should probably remove the last vestiges of password support and then do the key dance from the driver code. :)

**Comment by johnjelinek** [comment]
This transport config isn't working for me.
