### ISSUE TITLE
Waste time to download the chef provisioner

### ISSUE THREAD

**Issue by SydOps** [test-kitchen/kitchen-docker#218]
I like to use kitchen-docker as main kitchen test driver, in most case the speed is faster than kitchen-vagrant.

But every time when I run `kitchen test`, it always takes time to download chef package and waste at least 2 minutes for every driver. 
```
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 14.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=14.04&m=x86_64
         to file /tmp/install.sh.1126/metadata.txt
       trying wget...
       sha1	bc4a6642d6093b54de856da31f0651a56b0fdc8e
       sha256	f1cf5d0f6dd12d2d2296ec6d8dbb16363f8541f5c15298cafa70e65ff2b5a22f
       url	https://packages.chef.io/stable/ubuntu/14.04/chef_12.11.18-1_amd64.deb
       version	12.11.18
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/stable/ubuntu/14.04/chef_12.11.18-1_amd64.deb
         to file /tmp/install.sh.1126/chef_12.11.18-1_amd64.deb
       trying wget...
```
Here is the sample of `.kitchen.yml`
```
driver:
  name: docker

provisioner:
  name: chef_solo
```

How to reduce the time?

**Comment by coderanger** [comment]
See https://github.com/test-kitchen/kitchen-docker#provision_command

**Comment by SydOps** [comment]
Thanks, @coderanger 

Do you mean I need run below command to install chef directly? What's the different? Still takes 2 minutes (or longer) to download chef package.

      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash

Can I download the package first, let kitche to copy it to container and install?

**Comment by jjasghar** [comment]
Couldn't you create a local image with Chef already installed? And have that as your "base image?"

**Comment by coderanger** [comment]
The `provision_command` gets added to the generated Dockerfile so it will be cached via the docker layer system.

**Comment by SydOps** [comment]
@coderanger 

Not really, every time, I run with same setting, always download the chef package.

@jjasghar 

Seems this is the way I need go, thanks.

**Comment by coderanger** [comment]
Make sure you don't have the Chef version set to `true`, if you leave it as the default (`nil`) it will use the version cached in the container image.
