### ISSUE TITLE
docker images: service usage ?

### ISSUE THREAD

**Issue by juju4** [test-kitchen/kitchen-docker#222]
Hello,

As said in issue #221, I'm trying to use kitchen-docker for ansible testing instead of kitchen-vagrant(+virtualbox): Doing the test on ubuntu14.04 VM and ansible role https://github.com/juju4/ansible-adduser.

This simple role is working fine but as I tried with more advanced one like https://github.com/juju4/ansible-icinga2, it fails.
Failure happened on service eg doing a mysql operation, enabling a service or whatever background activity.
from code, it seems kitchen-docker runs only ssh but I'm unsure after the origin of docker images (docker hub?) and if any mecanism to use services inside like https://github.com/geerlingguy/drupal-vm/pull/456/files#diff-b1546b21a9366075f1e1245d7551eee6R11

is it possible?
how to make it work?

Thanks

**Comment by coderanger** [comment]
Ubuntu 14.04 uses Upstart. Upstart does not run correctly inside containers, thus this is not possible unfortunately. With 16.04+ (i.e. systemd) you can make it work by swapping the init command, but no go on Upstart.
