### ISSUE TITLE
Lack of documentation on installing the driver

### ISSUE THREAD

**Issue by farvour** [test-kitchen/kitchen-docker#224]
There seems to be some missing documentation on installing the driver. I have attempted multiple methods to get the gem installed, using the embedded ChefDK ruby gem etc but I still get this issue:

```
-----> Starting Kitchen (v1.10.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'docker' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

If I install the gem as a regular user, then I just get inspec loading issues:
```
chef gem install kitchen-docker-api
Fetching: archive-tar-minitar-0.5.2.gem (100%)
WARNING:  You don't have /home/tfarvour/.chefdk/gem/ruby/2.1.0/bin in your PATH,
	  gem executables will not run.
Successfully installed archive-tar-minitar-0.5.2
Fetching: docker-api-1.10.11.gem (100%)
Successfully installed docker-api-1.10.11
Fetching: kitchen-docker-api-0.4.0.gem (100%)
Successfully installed kitchen-docker-api-0.4.0
3 gems installed


 kitchen create
-----> Starting Kitchen (v1.10.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

**Comment by coderanger** [comment]
This project is `kitchen-docker`, not `kitchen-docker-api`. You seem to have crossed some streams, pick which you want to use. Sounds like you also need to `chef gem install kitchen-inspec` too.

**Comment by farvour** [comment]
Aghh!! You're right I didn't even pay attention to that.

In any case, here is a good way to get the right one installed via the chef gem:

```sudo chef gem install --no-user-install kitchen-docker```

**Comment by coderanger** [comment]
The correct command is `chef gem install kitchen-docker`.

**Comment by jlsjonas** [comment]
Could this be added to the documentation somewhere? had to go through a couple google results to stumble upon this; over 1 year after closure.

**Comment by jondkelley** [comment]
Bueller, did you hear @jlsjonas ?
