### ISSUE TITLE
Support development on macOS 10.12

### ISSUE THREAD

**Issue by timvisher** [test-kitchen/kitchen-docker#234]
I can't get the build working on macOS 10.12. I'm falling back to using a xenial vagrant box at the moment but It would be groovy to support 10.12 directly.

**Comment by coderanger** [comment]
You would have to be more specific. Docker does not run on macOS so you'll always need some kind of Linux box under the hood somewhere.

**Comment by timvisher** [comment]
Docker does run on macOS. https://docs.docker.com/engine/installation/mac/

**Comment by coderanger** [comment]
No, it doesn't. It uses xhyve under the hood to run a Linux VM for you. Docker is categorically incapable of running processes on macOS right now as the Darwin kernel lacks the needed APIs.

**Comment by timvisher** [comment]
Ah my apologies. What I meant by running on OS X is that there is support for running docker in macOS which is good enough for using it from the perspective of kitchen-docker. kitchen-docker doesn't care how or where docker is running so long as it can execute docker commands.

What this issue is about is being able to install the gem from the source directory on macOS. I'm assuming this is possible but I've been unsuccessful at it so far and have thus had to fall back to a xenial VM to do so. It'd be nice if no VM was needed other than the one required to run docker.

**Comment by coderanger** [comment]
I do all my dev on a Mac so again, you need to be more specific.

**Comment by timvisher** [comment]
Maybe what would be helpful is describing how to get it up and running on a Mac?

[This](https://gist.github.com/timvisher/a1405c862767ac6c5799c63e4075887b) is what's currently happening for me.

**Comment by coderanger** [comment]
The error seems pretty clear, nokogiri isn't able to compile because it can't find libxml2. Fix that :) The instructions for dev setup are the same as for every ruby gem ever, so I don't feel the need to duplicate them really. You're doing the right steps, just need to fix your libs.

**Comment by timvisher** [comment]
I had to follow the instructions here. https://github.com/sparklemotion/nokogiri/issues/1483

**Comment by timvisher** [comment]
I can't get the kitchen tests to run without modifying the `.kitchen.yml` file to include `use_sudo: false`. I can `sudo docker run hello-world` and `docker run hello-world` though. Any ideas?

**Comment by peterabbott** [comment]
It can depend on how you reference Docker. I think if you don't specify DOCKER_HOST envelope variable to the Unix socket it tries to use sudo to check. You could either set the env variable or override with Test Kitchens local override file, search for `.kitchen.local.yaml` for more info.
