### ISSUE TITLE
port forwarding documentation backwards?

### ISSUE THREAD

**Issue by dpalomin** [test-kitchen/kitchen-docker#236]
Is the port forwarding documentation at https://github.com/test-kitchen/kitchen-docker/#forward incorrect, or am I just misunderstanding?  

I am trying to forward a container port of 80 to 8888 on my host.  The documentation seems to suggest it should be

```
 forward: 
  - 8080:8080
  - 80:8888
```

But my testing only works when it is

```
  forward: 
  - 8080:8080
  - 8888:80
```

**Comment by blairham** [comment]
I think you're misunderstanding it. it's <host>:<container>
