### ISSUE TITLE
Managed /etc/sudoers breaks sudo actions for kitchen user

### ISSUE THREAD

**Issue by StephenKing** [test-kitchen/kitchen-docker#246]
With c05dbe9cafdf36f3f277fc1a5b0fdd0b06d59e1b, the following [line](https://github.com/test-kitchen/kitchen-docker/commit/c05dbe9cafdf36f3f277fc1a5b0fdd0b06d59e1b#diff-774b848acbb1b98e97bb4293c11174e1L241) has been _removed_:

    RUN echo '#{username} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/#{username}

This, however, now breaks the `kitchen verify` step (or any actions that require _sudo_ privileges), if the file `/etc/sudoers` is replaced during the chef run, e.g. using the [sudo cookbook](https://github.com/chef-cookbooks/sudo/blob/2318fa00e4c66d6a0b46dcc4d2a99e716d363d7e/recipes/default.rb#L41-L60). As `kitchen` user is removed from the file, it lacks sudo privileges afterwards.

Is there a solution that helps with both issues ("make sudo work on all platforms") and the replaced `/etc/sudoers`?

**Comment by coderanger** [comment]
Don't run the `sudo` cookbook when testing or reconfigure it to allow access to the `kitchen` user. This will be fixed in the future by moving away from `ssh`+`sudo` for command execution, assuming someone funds the works.

**Comment by StephenKing** [comment]
Thanks for the quick response, Noah. As some other commands are executed through `sudo`, I still need that. I will then keep the following snippet to keep `sudo` access for the `kitchen` user:

    sudo "kitchen" do
      user "kitchen"
      nopasswd true
      only_if { ENV['TEST_KITCHEN'] }
    end
