### ISSUE TITLE
Support to windows platform

### ISSUE THREAD

**Issue by tiagolo** [test-kitchen/kitchen-docker#259]
Guys,
with the new Windows Server docker container images, is it possible to add the support for this platform?

**Comment by darkn3rd** [comment]
Just to clarify, this is testing Windows containers on Windows host, and NOT testing Linux Docker containers on Windows Host.

**Comment by lmayorga1980** [comment]
It has been more than 2 years. Any news on this issue?

**Comment by jeffreycoe** [comment]
@lmayorga1980 Please see PR #340 as we’re attempting to add this functionality now.

**Comment by jeffreycoe** [comment]
Release 2.10 contains Windows support now. Please open a new issue if any problems are found using this release. Thanks.
