### ISSUE TITLE
Mapping a volume using a relative directory as a source

### ISSUE THREAD

**Issue by jamesla** [test-kitchen/kitchen-docker#263]
I am wanting to map a folder to my docker driver where the path is a relative folder. I've tried the following which doesn't work but illustrates what I am trying to achieve. 

`volume: ./:/vagrant/ansible`

Is this possible?

**Comment by peterabbott** [comment]
The volume attribute is a pass-through to the docker `-v` switch so you'll probably have to add absolute path. When I use docker directly I have to use absolute paths too.

**Comment by jamesla** [comment]
thanks the answer was using $(pwd)
