### ISSUE TITLE
Kitchen Converge - Sandbox directory has not yet been created

### ISSUE THREAD

**Issue by seusher** [test-kitchen/kitchen-docker#271]
# Description

I just started using kitchen-docker. I am able to run `kitchen create` just fine, the VM gets created, and I can SSH into it, but running `kitchen converge` fails saying the Sandbox directory has not yet been created.

I didn't see any report of this in the open or closed issues, but I am hoping someone else has encountered this error.

# Kitchen Converge

    PS C:\Users\seusher\Documents\Git\Chef\cookbooks\ubuntu-base> kitchen converge -l debug
    -----> Starting Kitchen (v1.7.3)
    D      [local command] BEGIN (docker >> NUL 2>&1)
    D      [local command] END (0m0.00s)
    D      Berksfile found at C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/Berksfile, loading Berkshelf
    D      Berkshelf 4.3.2 library loaded
    -----> Converging <default2-ubuntu:1404>...
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::ChefZero#create_sandox before trying to access the path.]
    >>>>>> ----------------------
    >>>>>> Please see .kitchen/logs/kitchen.log for more details
    >>>>>> Also try running `kitchen diagnose --all` for configuration

    D      ------Exception-------
    D      Class: Kitchen::ActionFailed
    D      Message: Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::ChefZero#create_sandox before trying to access the path.]
    D      ---Nested Exception---
    D      Class: Kitchen::ClientError
    D      Message: Sandbox directory has not yet been created. Please run Kitchen::Provisioner::ChefZero#create_sandox before trying to access the path.
    D      ------Backtrace-------
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/provisioner/base.rb:147:in `sandbox_path'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/provisioner/base.rb:156:in `cleanup_sandbox'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/provisioner/base.rb:78:in `ensure in call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/provisioner/base.rb:78:in `call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:373:in `block in converge_action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:513:in `call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:513:in `synchronize_or_call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:478:in `block in action'
    D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:477:in `action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:369:in `converge_action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:348:in `block in transition_to'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:347:in `each'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:347:in `transition_to'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/instance.rb:138:in `converge'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:176:in `public_send'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.7.3/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
    D      ----------------------

# Kitchen Diagnose --all

    PS C:\Users\seusher\Documents\Git\Chef\cookbooks\ubuntu-base> kitchen diagnose --all
    ---
    timestamp: 2017-07-24 20:00:10 UTC
    kitchen_version: 1.7.3
    plugins:
      driver:
        Docker:
          class: Kitchen::Driver::Docker
          version:
          api_version:
      provisioner:
        ChefZero:
          class: Kitchen::Provisioner::ChefZero
          version: 1.7.3
          api_version: 2
      transport:
        Ssh:
          class: Kitchen::Transport::Ssh
          version: 1.7.3
          api_version: 1
      verifier:
        Busser:
          class: Kitchen::Verifier::Busser
          version: 1.7.3
          api_version: 1
    loader:
      process_erb: true
      process_local: true
      process_global: true
      global_config:
      project_config:
        filename: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/.kitchen.yml
        raw_data:
          driver:
            name: docker
            use_sudo: false
            socket: npipe:////./pipe/docker_engine
          provisioner:
            name: chef_zero
            data_bags_path: C:\Chef\data_bags
            environments_path: C:\Users\seusher\Documents\Git\Chef\environments
            client_rb:
              environment: test
          platforms:
          - name: ubuntu:14.04
            driver_config:
              image: ubuntu:14.04
              platform: ubuntu
          suites:
          - name: default2
            run_list:
            - recipe[ubuntu-base::createazurefirewallrules]
      local_config:
        filename: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/.kitchen.local.yml
        raw_data:
          driver:
            name: docker
            use_sudo: false
          provisioner:
            name: chef_zero
          platforms:
          - name: ubuntu:14.04
            driver_config:
              image: ubuntu:14.04
              platform: ubuntu
          suites:
          - name: default2
            run_list:
            - recipe[ubuntu-base::createazurefirewallrules]
      combined_config:
        filename:
        raw_data:
          driver:
            name: docker
            use_sudo: false
            socket: npipe:////./pipe/docker_engine
          provisioner:
            name: chef_zero
            data_bags_path: C:\Chef\data_bags
            environments_path: C:\Users\seusher\Documents\Git\Chef\environments
            client_rb:
              environment: test
          platforms:
          - name: ubuntu:14.04
            driver_config:
              image: ubuntu:14.04
              platform: ubuntu
          suites:
          - name: default2
            run_list:
            - recipe[ubuntu-base::createazurefirewallrules]
    instances:
      default2-ubuntu:1404:
        platform:
          os_type: unix
          shell_type: bourne
        state_file:
          container_id: b84ffdbb1fe30572a4ee9dc71c76570ac1ae8211075cd833b3b979f552e4e329
          hostname: localhost
          image_id: 533967c81835
          last_action: converge
          port: 32768
          ssh_key: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/.kitchen/docker_id_rsa
          username: kitchen
        driver:
          binary: docker
          build_context: true
          build_options:
          cap_add:
          cap_drop:
          disable_upstart: true
          image: ubuntu:14.04
          instance_name: default2ubuntu1404-seusher-MININTNTBN8I8-t24lfu6c
          kitchen_root: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base
          log_level: :info
          name: docker
          platform: ubuntu
          private_key: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/.kitchen/docker_id_rsa
          privileged: false
          public_key: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/.kitchen/docker_id_rsa.pub
          publish_all: false
          remove_images: false
          run_command: "/usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes
            -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid"
          run_options:
          security_opt:
          socket: npipe:////./pipe/docker_engine
          test_base_path: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/test/integration
          tls: false
          tls_cacert:
          tls_cert:
          tls_key:
          tls_verify: false
          use_cache: true
          use_sudo: false
          username: kitchen
          wait_for_sshd: true
        provisioner:
          attributes: {}
          chef_client_path: "/bin/chef-client"
          chef_omnibus_install_options:
          chef_omnibus_url: https://www.chef.io/chef/install.sh
          chef_zero_host:
          chef_zero_port: 8889
          client_rb:
            environment: test
          clients_path:
          command_prefix:
          config_path:
          cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
          data_bags_path: C:/Chef/data_bags
          data_path:
          encrypted_data_bag_secret_key_path:
          environments_path: C:/Users/seusher/Documents/Git/Chef/environments
          ftp_proxy:
          http_proxy:
          https_proxy:
          json_attributes: true
          kitchen_root: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base
          log_file:
          log_level: auto
          name: chef_zero
          nodes_path:
          profile_ruby: false
          require_chef_omnibus: true
          roles_path:
          root_path: "/tmp/kitchen"
          ruby_bindir: "/embedded/bin"
          run_list:
          - recipe[ubuntu-base::createazurefirewallrules]
          sudo: true
          sudo_command: sudo -E
          test_base_path: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/test/integration
        transport:
          compression: true
          compression_level: 6
          connection_retries: 5
          connection_retry_sleep: 1
          connection_timeout: 15
          keepalive: true
          keepalive_interval: 60
          kitchen_root: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base
          log_level: :info
          max_wait_until_ready: 600
          name: ssh
          port: 22
          ssh_key:
          test_base_path: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/test/integration
          username: root
        verifier:
          busser_bin: "/tmp/verifier/bin/busser"
          chef_omnibus_root: "/opt/chef"
          command_prefix:
          ftp_proxy:
          http_proxy:
          https_proxy:
          kitchen_root: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base
          log_level: :info
          name: busser
          root_path: "/tmp/verifier"
          ruby_bindir: "/opt/chef/embedded/bin"
          sudo: true
          sudo_command: sudo -E
          suite_name: default2
          test_base_path: C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/test/integration
          version: busser

**Comment by coderanger** [comment]
That is a very old Test Kitchen, the current version is 1.16. Can you try with something newer?

**Comment by seusher** [comment]
No luck with the newer version of test kitchen:

    PS C:\Users\seusher\Documents\Git\Chef\cookbooks\ubuntu-base> kitchen converge -l debug
    -----> Starting Kitchen (v1.16.0)
    D      [local command] BEGIN (docker >> NUL 2>&1)
    D      [local command] END (0m0.00s)
    D      Berksfile found at C:/Users/seusher/Documents/Git/Chef/cookbooks/ubuntu-base/Berksfile, loading Berkshelf
    D      Berkshelf 6.2.0 library loaded
    -----> Converging <default2-ubuntu:1404>...
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: 1 actions failed.
    >>>>>>     Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::ChefZero#create_sandox before trying to access the path.] on default2-ubuntu:1404
    >>>>>> ----------------------
    >>>>>> Please see .kitchen/logs/kitchen.log for more details
    >>>>>> Also try running `kitchen diagnose --all` for configuration

    D      ------Exception-------
    D      Class: Kitchen::ActionFailed
    D      Message: 1 actions failed.
    >>>>>>     Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::ChefZero#create_sandox before trying to access the path.] on default2-ubuntu:1404
    D      ----------------------
    D      ------Backtrace-------
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
    D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
    D      C:/opscode/chefdk/bin/kitchen:275:in `load'
    D      C:/opscode/chefdk/bin/kitchen:275:in `<main>'
    D      ----End Backtrace-----
    D      -Composite Exception--
    D      Class: Kitchen::ActionFailed
    D      Message: Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::ChefZero#create_sandox before trying to access the path.] on default2-ubuntu:1404
    D      ----------------------
    D      ------Backtrace-------
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:154:in `sandbox_path'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:163:in `cleanup_sandbox'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:85:in `ensure in call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:85:in `call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
    D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
    D      ----End Backtrace-----
    D      ---Nested Exception---
    D      Class: Kitchen::ActionFailed
    D      Message: Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::ChefZero#create_sandox before trying to access the path.]
    D      ----------------------
    D      ------Backtrace-------
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:154:in `sandbox_path'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:163:in `cleanup_sandbox'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:85:in `ensure in call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:85:in `call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
    D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
    D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
    D      ----End Backtrace-----

**Comment by jeffreycoe** [comment]
@seusher As this issue is a few years old at this point, I'm going to close this out due to inactivity. Please open a new issue if this problem still occurs with the latest release of test kitchen and the kitchen-docker gem. Thanks!
