### ISSUE TITLE
Clarify project maintainer/s

### ISSUE THREAD

**Issue by wjordan** [test-kitchen/kitchen-docker#277]
While discussing the `kitchen-dokken` project in someara/kitchen-dokken#130, @cheeseplus [commented](https://github.com/someara/kitchen-dokken/issues/130#issuecomment-336870801) that the `kitchen-docker` project was not owned/maintained by Chef, which came to me as a bit of a surprise:

> To be clear, kitchen-docker is in no way the official driver. Regardless of which one came first, WE (Chef) recommend kitchen-dokken and it's what we include in the ChefDK. That said, neither "docker" driver is owned or maintained by Chef Co.

I had always assumed that `kitchen-docker` was the official maintained-by-Chef driver, since this project's current GitHub owner is the `test-kitchen` organization, which itself is "Maintained by Chef" according to the [public website](http://kitchen.ci/).

If it's not the case that `kitchen-docker` is "Maintained by Chef" like Test Kitchen, this difference should either be clarified in this project's README, or this project's GitHub ownership should be reassigned to the current maintainer.

**Comment by coderanger** [comment]
The Kitchen website is maintened by Chef Software. The actual Test Kitchen tool, and all drivers, are maintained by various volunteers. This includes kitchen-docker, for which I am the only currently active maintainer.
