### ISSUE TITLE
Consider publishing docker images on Docker Hub

### ISSUE THREAD

**Issue by ferrarimarco** [test-kitchen/kitchen-docker#284]
`kitchen-docker` repeats the same `docker build` actions every time it needs to spin up a test.

Did you consider publishing docker images on Docker Hub for each supported platform?

This will considerably speed up each test suite, as this enhancement will spare us from the aforementioned `docker build` step.

Thoughts?

**Comment by jeffreycoe** [comment]
Unfortunately, there aren't enough maintainers on this project to support creating and publishing docker images for each platform at this time.

We can always revisit this if it becomes a critical feature the community needs. Contributions are always welcome, too.
