### ISSUE TITLE
Build Image Automatically From Dockerfile

### ISSUE THREAD

**Issue by onetwopunch** [test-kitchen/kitchen-docker#287]
I've taken a look at the `dockerfile` key and it doesn't seem very intuitive, especially with the `build_context` flag. 

Not only does it replace the default Dockerfile, which means everyone who overrides with the `dockerfile` attribute has to implement the SSH logic necessary for the kitchen user to login, but if the Dockerfile specified references a relative file to add or volume to mount, there is an error. This is because in https://github.com/test-kitchen/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L312 there is an assumption that the Dockerfile is an isolated unit in the same directory as the `.kitchen.yml`.

This can all obviously be solved by creating an image and specifying it, but I can see many use cases (my current one in particular) where it would be useful to have the Dockerfile attribute not construct a Dockerfile from a template in a temporary file, but rather build an image from that Dockerfile and then base the test kitchen docker file on that. This way if you have multiple images that need to be built first, you can keep all the Dockerfiles for those images in the cookbook alongside the tests. Please let me know what you think, I'm happy to elaborate more and create a PR, but I want to make sure it's in line with what you all are thinking first.

What I'm imagining is a `pre_build_image: true|false` as part of the config. If that is false, everything functions as usual, if it's true, then the `image` here:https://github.com/test-kitchen/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L184 could be:

```ruby
from = "FROM #{prebuilt_image || config[:image]}"
```

And then later you'd have something like this:

```ruby
def prebuilt_image
  return if config[:image]
  if config[:dockerfile]
    cmd = "build"
    cmd << " --no-cache" unless config[:use_cache]
    extra_build_options = config_to_options(config[:build_options])
    cmd << " #{extra_build_options}" unless extra_build_options.empty?
    filename = Shellwords.escape(File.expand_path(config[:dockerfile]))
    build_context = File.dirname(filename)
    docker_command("#{cmd} -f #{filename} #{build_context}")
  end
end
```

Please let me know your thoughts. Again, I'd be happy to do the work on this.

**Comment by coderanger** [comment]
The plan is instead to move away from using SSH at all and do things more like kitchen-dokken and kitchen-kubernetes so that upstream base images can be used without modification. For now, I do recommend using the `dockerfile` option, https://github.com/poise/poise-boiler/blob/master/lib/poise_boiler/helpers/kitchen/Dockerfile.erb is the one most of my projects are using for now.
