### ISSUE TITLE
Kitchen Verify

### ISSUE THREAD

**Issue by mccoyaoife** [test-kitchen/kitchen-docker#324]
When I run kitchen verify, it tries to install ruby, bundler and serverspec. 

Verifying <default-ubuntu>...
build	31-Jan-2019 11:11:58	       Installing ruby, bundler and serverspec remotely on server

Reading state information... Done
build	31-Jan-2019 11:12:04	       The following extra packages will be installed:
build	31-Jan-2019 11:12:04	         libruby1.9.1 ruby1.9.1
build	31-Jan-2019 11:12:04	       Suggested packages:
build	31-Jan-2019 11:12:04	         ri ruby-dev ruby1.9.1-examples ri1.9.1 graphviz ruby1.9.1-dev ruby-switch
build	31-Jan-2019 11:12:04	       The following NEW packages will be installed:
build	31-Jan-2019 11:12:04	         libruby1.9.1 ruby ruby1.9.1
build	31-Jan-2019 11:12:04	       0 upgraded, 3 newly installed, 0 to remove and 19 not upgraded.
Setting up ruby (1:1.9.3.4) ...
build	31-Jan-2019 11:12:10	       Setting up ruby1.9.1 (1.9.3.484-2ubuntu1.13) ...
build	31-Jan-2019 11:12:10	       Setting up libruby1.9.1 (1.9.3.484-2ubuntu1.13) ...
build	31-Jan-2019 11:12:10	       Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
build	31-Jan-2019 11:12:11	       Fetching: bundler-2.0.1.gem
Fetching: bundler-2.0.1.gem (100%)
build	31-Jan-2019 11:12:11	       ERROR:  Error installing bundler:
build	31-Jan-2019 11:12:11	       	bundler requires Ruby version >= 2.3.0.

Then i get the error above. With the new release of bundler 2.0 it no longer supports ruby versions lower then 2.3.0. Kitchen verify automatically installs a lower version of ruby 1.9 - can this be updated to install a version great than 2.3.0? 

Thanks

**Comment by damacus** [comment]
Hey, 

this output would suggest you're using the serverspec verifier, rather than something like inspec which will run remotely.

**Comment by coderanger** [comment]
Also normally busser-serverspec uses Chef's Ruby rather than the distro Ruby.

**Comment by jeffreycoe** [comment]
Based on previous comments, it looks as if this issue is not related to kitchen-docker. Please open a new issue if there is a problem related to this gem after testing with the latest release. Thanks!
