### ISSUE TITLE
issue running kitchen-docker on osx mojave

### ISSUE THREAD

**Issue by johnypony3** [test-kitchen/kitchen-docker#326]
# issues

i am not able to use docker with test-kitchen on mac mojave

## remedies attempted

* use_sudo:         false
* privileged:       true
* socket:           unix:///var/run/docker.sock
* resetting docker desktop

## kitchen.yml file:

```
---
driver:
  name:            docker
  use_sudo:        false
  privileged:      true
provisioner:
  name:            chef_zero
  log_level:       info
platforms:
  - name:          ubuntu-14.04
    driver_config:
      image:       ubuntu-upstart:14.04
      platform:    ubuntu
suites:
  - name:          default
    run_list:
      - recipe[base_tester::default]

```

## error:

```
-----> Starting Kitchen (v1.24.0)
-----> Creating <default-ubuntu-1404>...
       Sending build context to Docker daemon  1.704MB
       Error response from daemon: ENV must have two arguments
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20190227-31300-lumals . ----
STDOUT: Sending build context to Docker daemon  1.704MB
STDERR: Error response from daemon: ENV must have two arguments
---- End output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20190227-31300-lumals . ----
Ran docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20190227-31300-lumals . returned 1] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## versions:

* sw_vers -productVersion (mac version)
  * 10.14.3
* docker -v
  * Docker version 18.09.2, build 6247962
* Docker Desktop
  * Version 2.0.0.3 (31259)
  * Channel: stable
  * 8858db33c8
* kitchen -v
  * Test Kitchen version 1.24.0
* chef -v
  * Chef Development Kit Version: 3.5.13
  * chef-client version: 14.7.17
  * delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
  * berks version: 7.0.6
  * kitchen version: 1.23.2
  * inspec version: 3.0.52
* ruby -v
  * ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
* gem list
  * addressable (2.5.2)
  * berkshelf (7.0.7)
  * bigdecimal (default: 1.4.1)
  * builder (3.2.3)
  * bundler (default: 1.17.3)
  * celluloid (0.17.4)
  * celluloid-essentials (0.20.5)
  * celluloid-extras (0.20.5)
  * celluloid-fsm (0.20.5)
  * celluloid-pool (0.20.5)
  * celluloid-supervision (0.20.6)
  * chef (14.10.9)
  * chef-config (14.10.9)
  * chef-zero (14.0.11)
  * cleanroom (1.0.0)
  * cmath (default: 1.0.0)
  * coderay (1.1.2)
  * concurrent-ruby (1.1.4)
  * csv (default: 3.0.4)
  * date (default: 2.0.0)
  * dbm (default: 1.0.0)
  * did_you_mean (1.3.0)
  * diff-lcs (1.3)
  * e2mmap (default: 0.1.0)
  * erubis (2.7.0)
  * etc (default: 1.0.1)
  * faraday (0.15.4)
  * fcntl (default: 1.0.0)
  * ffi (1.10.0)
  * ffi-yajl (2.3.1)
  * fiddle (default: 1.0.0)
  * fileutils (default: 1.1.0)
  * forwardable (default: 1.2.0)
  * fuzzyurl (0.9.0)
  * gdbm (default: 2.0.0)
  * gem-wrappers (1.4.0)
  * gssapi (1.2.0)
  * gyoku (1.3.1)
  * hashie (3.6.0)
  * highline (1.7.10)
  * httpclient (2.8.3)
  * iniparse (1.4.4)
  * io-console (default: 0.4.7)
  * ipaddr (default: 1.2.2)
  * ipaddress (0.8.3)
  * irb (default: 1.0.0)
  * json (default: 2.1.0)
  * kitchen-docker (2.8.0, 0.10.0)
  * kitchen-vagrant (1.4.0, 0.11.3)
  * libyajl2 (1.2.0)
  * little-plugger (1.1.4)
  * logger (default: 1.3.0)
  * logging (2.2.2)
  * matrix (default: 0.1.0)
  * method_source (0.9.2)
  * minitar (0.8)
  * minitest (5.11.3)
  * mixlib-archive (0.4.19)
  * mixlib-authentication (2.1.1)
  * mixlib-cli (1.7.0)
  * mixlib-config (2.2.18)
  * mixlib-install (3.11.11)
  * mixlib-log (2.0.9)
  * mixlib-shellout (2.4.4)
  * mixlib-versioning (1.2.7)
  * molinillo (0.6.6)
  * multi_json (1.13.1)
  * multipart-post (2.0.0)
  * mutex_m (default: 0.1.0)
  * net-scp (1.2.1)
  * net-sftp (2.1.2)
  * net-ssh (4.2.0)
  * net-ssh-gateway (2.0.0, 1.3.0)
  * net-ssh-multi (1.2.1)
  * net-telnet (0.2.0, 0.1.1)
  * nori (2.6.0)
  * octokit (4.13.0)
  * ohai (14.8.10)
  * openssl (default: 2.1.2)
  * ostruct (default: 0.1.0)
  * plist (3.5.0)
  * power_assert (1.1.3)
  * prime (default: 0.1.0)
  * proxifier (1.0.3)
  * pry (0.12.2)
  * psych (default: 3.1.0)
  * public_suffix (3.0.3)
  * rack (2.0.6)
  * rake (12.3.2)
  * rdoc (default: 6.1.0)
  * retryable (2.0.4)
  * rexml (default: 3.1.9)
  * rspec (3.8.0)
  * rspec-core (3.8.0)
  * rspec-expectations (3.8.2)
  * rspec-its (1.2.0)
  * rspec-mocks (3.8.0)
  * rspec-support (3.8.0)
  * rspec_junit_formatter (0.2.3)
  * rss (default: 0.2.7)
  * rubyntlm (0.6.2)
  * rubyzip (1.2.2)
  * rvm (1.11.3.9)
  * safe_yaml (0.9.7)
  * sawyer (0.8.1)
  * scanf (default: 1.0.0)
  * sdbm (default: 1.0.0)
  * semverse (3.0.0)
  * serverspec (2.41.3)
  * sfl (2.3)
  * shell (default: 0.7)
  * solve (4.0.2)
  * specinfra (2.76.9)
  * stringio (default: 0.0.2)
  * strscan (default: 1.0.0)
  * sync (default: 0.5.0)
  * syslog-logger (1.6.8)
  * systemu (2.6.5)
  * test-kitchen (1.24.0, 1.0.0.beta.3)
  * test-unit (3.2.9)
  * thor (0.20.3)
  * thwait (default: 0.1.0)
  * timers (4.3.0)
  * tomlrb (1.2.8)
  * tracer (default: 0.1.0)
  * uuidtools (2.1.5)
  * webrick (default: 1.4.2)
  * winrm (2.3.1)
  * winrm-elevated (1.1.1)
  * winrm-fs (1.3.2)
  * wmi-lite (1.0.2)
  * xmlrpc (0.3.0)
  * zlib (default: 1.0.0)

**Comment by coderanger** [comment]
You would need to things up for remote docker, which is what Docker for Mac uses. Check what your docker host URI looks like and use that.

**Comment by johnypony3** [comment]
can you elaborate?

>need to things up

what?

how do i check the uri?

>
