### ISSUE TITLE
Gem v2.9.0 doesn't include the docker transport

### ISSUE THREAD

**Issue by robertlabrie** [test-kitchen/kitchen-docker#352]
It's most likely that I'm really bad at this, but when trying to use transport name:docker I get `Could not load the 'docker' transport from the load path.` and when I look in `gem environment gemdir`/gems/kitchen-docker-2.9.0/lib/kitchen there is no transport directory. This is weird, because here in GH it's sitting there.

I can install the gem from GH but I'm wondering if maybe the lib is missing from the gemspec?

**Comment by yeoldegrove** [comment]
As stated here https://github.com/test-kitchen/kitchen-docker/pull/340#issuecomment-533171077, nobody is able to relase this gem for over 3 monthe now...
@stuartpreston @jeffreycoe When will this finally be done?

**Comment by stuartpreston** [comment]
Yes I'm afraid it's difficult to say when this will happen. This project is fully staffed by volunteers and a limited number of those volunteers have the ability to build/release the gem. Until then, to get the latest fixes and patches, you will need to build the gem locally from the `master` branch and then install it into your environment.

**Comment by ryandharper** [comment]
@stuartpreston Could you provide instructions on how to build the gem locally in the meantime?

**Comment by stuartpreston** [comment]
Sure, you clone the repo and then:

`gem build .\kitchen-docker.gemspec`
`gem install .\kitchen-docker-version.gem`

If you’re installing into the Chef DK or Workstation Ruby then prefix these commands with `chef`

**Comment by ryandharper** [comment]
Thanks!

**Comment by jeffreycoe** [comment]
@robertlabrie We were able to get a new release created, and version 2.10 contains the new docker transport. Please open a new issue if you have any problems with using this release.
