### ISSUE TITLE
There does not appear to be a way to clean up volumes created by kitchen-docker

### ISSUE THREAD

**Issue by terminalmage** [test-kitchen/kitchen-docker#362]
When using the [volume](https://github.com/test-kitchen/kitchen-docker/blob/2021133/README.md#volume) driver configuration in the documented way, Docker creates a new volume without a specified name, resulting in this new volume just being given a sha256 checksum as a name. Once the container is destroyed, this volume is left behind.

If this is left to run in a CI/CD system, there will soon be many unused volumes. I hope I am just missing something and there is a way to clean them up that I haven't seen yet. If not, then this is something we should look into adding.

Incidentally, since what I am testing is behavior for specific hardware profiles (in which /some/path) is a mount point), a much better solution for me would be to have Docker's `--mount` parameter implemented, so that I can just use tmpfs for this mountpoint.

**Comment by terminalmage** [comment]
I've just added support for the `--mount` option in #363.

**Comment by ersmith** [comment]
If you add `run_options: --rm` it will remove any anonymous volumes. This does have a few side effects:
* It removes the filesystem after the container stops which can make troubleshooting tougher (fixable by removing it as needed).
* This breaks (results in an error) when you run `kitchen destroy`. This raises issues though as the `kitchen destroy` exit code (20) is the same as a failed test run.

All of this being said, this is an issue with docker volumes in general.

**Comment by terminalmage** [comment]
Yeah, this is a byproduct of using the `-v` argument without a volume name or path. It could theoretically be solved by doing some parsing on the paths in `volumes` and creating unique volume names which can be cleaned in a later `kitchen destroy`.

However, according to the `docker-run` manpage:

```
See also --mount, which is the successor of --tmpfs and --volume.  Even though
there is no plan to deprecate --volume, usage of --mount is recommended.
```

Given this, and the fact that my PR to introduce support for the `--mount` parameter has been merged and is in an official release of kitchen-docker, I wouldn't be opposed to closing this as WONTFIX.

**Comment by terminalmage** [comment]
Closing per the above comment.
