### ISSUE TITLE
Create new release of kitchen-docker gem

### ISSUE THREAD

**Issue by jeffreycoe** [test-kitchen/kitchen-docker#365]
Over the past year, we've added quite a bit of updates to this gem and have been requesting to get a new release of it pushed to rubygems. I'd like to propose that we use this issue to track any issues or updates we need so we can get a new release pushed to the community. I know there are some teams who use this gem for testing other things besides Chef cookbooks.

Would @tas50 @stuartpreston or anyone else from Chef or Test Kitchen be able to respond on when we can get a new release pushed or if there is anything else needed?

I would invite anyone else from the community to provide any feedback or comments regarding a new release of this gem.

Thanks

**Comment by SuperQ** [comment]
CC: @portertech @coderanger who also have access to the [kitchen-docker](https://rubygems.org/gems/kitchen-docker) gem account.

**Comment by stuartpreston** [comment]
I feel the need to respond as I keep getting tagged but I do not have the right to build and push this gem I am afraid. As I understand it the gem is not used with prescribed Chef/Chef Workstation documented workflows and as such we need one of the willing volunteers (and I repeat they are *volunteers*) to give up their time to build, test and release this gem.

**Comment by SuperQ** [comment]
@stuartpreston Or, if one of the people who own the gem could expand the list of volunteers capable of doing the work instead.

**Comment by peterabbott** [comment]
This has been an ongoing thing with the project. When I was using kitchen-docker I ended up forking and managing a version in our internal work repo because could never get changes released. There are several forked versions with slightly different names, although not seen how active they are lately.

**Comment by jeffreycoe** [comment]
Closing issue as 2.10 has been released.
