### ISSUE TITLE
File transfer bottleneck

### ISSUE THREAD

**Issue by DevonVille** [test-kitchen/kitchen-docker#43]
Not sure if it's specific to the docker driver, or test kitchen as a whole,
but I experience a bottleneck when I try to converge, saying:
    Transferring files to <default-centos-64>
It takes a while until the files are actually being transferred, and the converge starts.
Can this be resolved by using a mount for the files instead?

**Comment by glenjamin** [comment]
Kitchen 1.4 now seems to have the ability to add custom user-selectable transports - see https://github.com/coderanger/kitchen-sync/commit/70726a6be588748b4c69dc2a35a4a85cb99e532c for an example.

Could this issue be re-opened? It seems like a `docker-volume` transport could be very powerful. there's also potentially the option to skip SSH entirely and use `docker exec -it bash` I think.
