### ISSUE TITLE
Set container name

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/kitchen-docker#79]
Just so I don't forget, it would be nice to have the container name set to something useful like the full suite name (plus random bits or time) so I can figure out which tests are using all my RAM.

**Comment by portertech** [comment]
This would be handy :+1: master now has `instance_name`, we could add another config option to set instance_name to the suite instance name.

**Comment by lucymhdavies** [comment]
Looks like
https://github.com/test-kitchen/kitchen-docker/commit/bbefea6f043723792fca7a59db5146d44db254a2
and
https://github.com/test-kitchen/kitchen-docker/commit/deb1d35cd73b12e824ae6f75c9fce989ae6293e5
should do this.

I look forward to 2.6.0 :)

**Comment by jeffreycoe** [comment]
Closing as this issue was fixed in an earlier release.
