### ISSUE TITLE
Cannot destroy container

### ISSUE THREAD

**Issue by tknerr** [test-kitchen/kitchen-docker#98]
Hi!

I'm running test-kitchen with the kitchen-docker driver on CircleCI. Getting this error during a `kitchen test` run during the destroy phase:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [Expected process to exit with [0], but received '1'
---- Begin output of sudo -E docker -H unix:///var/run/docker.sock rm 0eae74f4d59d1556449cf00051ac4585a49bf3712453e93a26983dff665e448c ----
STDOUT: 
STDERR: Error response from daemon: Cannot destroy container 0eae74f4d59d1556449cf00051ac4585a49bf3712453e93a26983dff665e448c: Driver btrfs failed to remove root filesystem 0eae74f4d59d1556449cf00051ac4585a49bf3712453e93a26983dff665e448c: Failed to destroy btrfs snapshot: operation not permitted
time="2015-01-13T16:43:50Z" level="fatal" msg="Error: failed to remove one or more containers"
---- End output of sudo -E docker -H unix:///var/run/docker.sock rm 0eae74f4d59d1556449cf00051ac4585a49bf3712453e93a26983dff665e448c ----
Ran sudo -E docker -H unix:///var/run/docker.sock rm 0eae74f4d59d1556449cf00051ac4585a49bf3712453e93a26983dff665e448c returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

More details:

 * full build log: https://circleci.com/gh/tknerr/sample-toplevel-cookbook/22
 * .kitchen.yml: https://github.com/tknerr/sample-toplevel-cookbook/blob/0182899dc6191033d83be5aa2d098a2451e39ba5/circleci/.kitchen.docker.yml
 * circleci.yml: https://github.com/tknerr/sample-toplevel-cookbook/blob/0182899dc6191033d83be5aa2d098a2451e39ba5/circle.yml

Any ideas?

**Comment by amaltson** [comment]
:+1:

**Comment by peterabbott** [comment]
This is a strange one to replicate. Only seems to happen when using the local socket to communicate with the Docker hosted instead of TCP (ie. Boot2Docker)

**Comment by peterabbott** [comment]
Looks like it might be the way that the Docker container in Circle CI handles the stop event. After calling stop, the container no longer exists despite not be called with --rm 

I was able to get it to work after update the driver, checkout the branch: 
https://github.com/peterabbott/kitchen-docker/tree/bugfix/98

Sample Circle CI job that previously failed, but now passes
https://circleci.com/gh/peterabbott/testing.infrastructure/9

The fix might need some extra tidyup around when to actually fail??

**Comment by kainz** [comment]
@tknerr since your sample-toplevel-cookbook isn't around anymore... were you running docker in docker perchance?

**Comment by tknerr** [comment]
@kainz oh it is still around, just not that branch anymore ;-)

So here's the example now on master:
https://github.com/tknerr/sample-toplevel-cookbook/blob/master/.kitchen.docker.yml
https://github.com/tknerr/sample-toplevel-cookbook/blob/master/circle.yml
https://circleci.com/gh/tknerr/sample-toplevel-cookbook/tree/master

**Comment by coderanger** [comment]
This smells like a Docker bug, closing this out.
